### ISSUE TITLE
What if secure-random is not supported?

### ISSUE THREAD

**Issue by jcalfee** [jprichardson/secure-random#2]
It would be nice to see a note in the documentation that says how to detect this condition.  Will the library always fail?  And how will it fail?

**Comment by jprichardson** [comment]
Hmm. Do you think just putting a section that states that an error will be thrown with the message as seen here (https://github.com/jprichardson/secure-random/blob/master/lib/secure-random.js#L24) is good enough?

**Comment by jcalfee** [comment]
yes, basically anything will do ... that really helps complete the library, knowing how it will report the absents of a secure random.  Thanks..
